#!/bin/bash

file=$(find $HOME -type f | dmenu -i  -l 10 -p "Curl 0x0.st:")
[ "$(printf "No\\nYes" | dmenu -i -p "Do you really want to upload to curl?")" = "Yes" ] && curl -F "file=@$file" 0x0.st | xclip -selection c && notify-send "📁 Copied Link"
