#!/bin/sh


chosen=$(cut -d ';' -f1 ~/.local/share/shownotes | dmenu -i -l 10 | sed 's/^\(.*\)_.*$/\1/')

[ -z "$chosen" ] && exit

if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	printf "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
