#!/bin/sh

wget -nc -O ~/Documents/News/The_Hindu-$(date +%d_%B_%Y).pdf -P ~/Documents/News/ "https://drive.google.com/uc?export=download&id=$(curl "https://iasbano.com/the-hindu-pdf-download-1.php" | grep drive | grep -Eo '(http|https)://[^?"]+' | cut -d/ -f6 | head -n 1)"

cd ~/Documents/News/
zathura The_Hindu-$(date +%d_%B_%Y).pdf
