#!/bin/bash

curl -s -L "https://www.vocabulary.com/dictionary/randomword" | grep -A8 "word-area" | sed -n -e 4p -e 8p -e 9p | sed 's/^[ \t]*//;s/[ \t]*$//' > ~/.cache/vocab1.txt
head -n 1 ~/.cache/vocab1.txt | tail -1 | cut -d "\"" -f2 > ~/.cache/vocab2.txt
sed -e 's/<[^>]*>//g' ~/.cache/vocab1.txt >> ~/.cache/vocab2.txt
sed -i 's/^\s*./\U&\E/g' ~/.cache/vocab2.txt
seq 4 | sed '3G' ~/.cache/vocab2.txt
