#!/bin/bash

if
	[ -n "$( echo "$(sed -n -e '$p' /run/user/1001/clipmenu.6.ram/line_cache)" | sed -n '/.pdf/p')" ]
then
	 wget -P ~/vimwiki/wgetpdf/ $(xclip -o) && zathura $(ls -tu ~/vimwiki/wgetpdf/* | head -n 1)
else
	 tabbed -c zathura $(shuf -n5 -e ~/vimwiki/Wikipedia/*.pdf) -e
fi
